package com.workruit.us.application.repositories;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.workruit.us.application.models.ApplicantDetails;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Repository
public interface ApplicantDetailsRepository extends JpaRepository<ApplicantDetails, Long> {
	ApplicantDetails findByApplicantId(Long applicantId);

	@Query("select u from ApplicantDetails u where u.applicantId in (?1)")
	List<ApplicantDetails> findByUsersDetails(List<Long> applicantIds);

	List<ApplicantDetails> findAllByApplicantIdIn(Set<Long> applicantIds);
	void deleteByApplicantId(Long applicantId);
}
