package com.workruit.us.application.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.workruit.us.application.models.Benefits;

/**
* Generated by Spring Data Generator on 25/11/2022
*/
@Repository
public interface BenefitsRepository extends JpaRepository<Benefits, Integer> {

}
