package com.workruit.us.application.repositories;

import com.workruit.us.application.models.Department;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Repository
public interface DepartmentRepository extends JpaRepository<Department, Long> {
    Department findByName(String name);

    @Query("select d from Department d where d.departmentId in (?1)")
    Department findByDepartmentId(Long id);
}
