package com.workruit.us.application.repositories;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.workruit.us.application.models.EducationHistory;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Repository
public interface EducationHistoryRepository extends JpaRepository<EducationHistory, Long> {
	List<EducationHistory> findByApplicantId(Long applicantId);

	void deleteByApplicantId(Long applicantId);

	List<EducationHistory> findAllByApplicantIdIn(Set<Long> applicantIds);
}
