package com.workruit.us.application.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.workruit.us.application.models.Internship;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Repository
public interface InternshipRepository extends JpaRepository<Internship, Long> {
	List<Internship> findByApplicantId(Long applicantId);

	void deleteByApplicantId(Long applicantId);
}
