package com.workruit.us.application.repositories;

import com.workruit.us.application.models.JobFunction;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Repository
public interface JobFunctionRepository extends JpaRepository<JobFunction, Integer> {
    JobFunction findByJobFunctionNameIgnoreCase(String name);

    JobFunction findByJobFunctionName(String name);
}
