package com.workruit.us.application.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.workruit.us.application.models.JobQuestion;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Repository
public interface JobQuestionRepository extends JpaRepository<JobQuestion, Long> {
	

	@Query(value = "DELETE FROM job_question where job_post_id = ?1", nativeQuery = true)
    void deleteByJobPostId(long jobId);

    void deleteByQuestionId(long questionId);

}
