package com.workruit.us.application.repositories;

import com.workruit.us.application.models.JobSkills;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Repository
public interface JobSkillsRepository extends JpaRepository<JobSkills, Integer> {
    JobSkills findBySkillNameIgnoreCase(String skillName);

    JobSkills findBySkillName(String skillName);
}
