package com.workruit.us.application.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.workruit.us.application.models.SocialMediaLinks;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Repository
public interface SocialMediaLinksRepository extends JpaRepository<SocialMediaLinks, Long> {
	List<SocialMediaLinks> findByApplicantId(Long applicantId);
	void deleteByApplicantId(Long applicantId);
}
