package com.workruit.us.application.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.workruit.us.application.repositories.ApplicantVerificationRepository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Component
public class ApplicantVerificationService {

    private final ApplicantVerificationRepository applicantVerificationRepository;

    @Autowired
    public ApplicantVerificationService(ApplicantVerificationRepository applicantVerificationRepository) {
        this.applicantVerificationRepository = applicantVerificationRepository;
    }

}
