package com.workruit.us.application.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.workruit.us.application.repositories.JobFunctionRepository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Component
public class JobFunctionService {

    private final JobFunctionRepository jobFunctionRepository;

    @Autowired
    public JobFunctionService(JobFunctionRepository jobFunctionRepository) {
        this.jobFunctionRepository = jobFunctionRepository;
    }

}
