package com.workruit.us.application.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.workruit.us.application.repositories.JobQuestionRepository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Component
public class JobQuestionService {

    private final JobQuestionRepository jobQuestionRepository;

    @Autowired
    public JobQuestionService(JobQuestionRepository jobQuestionRepository) {
        this.jobQuestionRepository = jobQuestionRepository;
    }

}
