package com.workruit.us.application.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.workruit.us.application.repositories.JobSkillsRepository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Component
public class JobSkillsService {

    private final JobSkillsRepository jobSkillsRepository;

    @Autowired
    public JobSkillsService(JobSkillsRepository jobSkillsRepository) {
        this.jobSkillsRepository = jobSkillsRepository;
    }

}
