package com.workruit.us.application.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.workruit.us.application.repositories.MobileVerificationRepository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Component
public class MobileVerificationService {

    private final MobileVerificationRepository mobileVerificationRepository;

    @Autowired
    public MobileVerificationService(MobileVerificationRepository mobileVerificationRepository) {
        this.mobileVerificationRepository = mobileVerificationRepository;
    }

}
