package com.workruit.us.application.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.workruit.us.application.repositories.SupplementalPayRepository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Component
public class SupplementalPayService {

    private final SupplementalPayRepository supplementalPayRepository;

    @Autowired
    public SupplementalPayService(SupplementalPayRepository supplementalPayRepository) {
        this.supplementalPayRepository = supplementalPayRepository;
    }

}
