package com.workruit.us.application.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.workruit.us.application.repositories.UserVerificationRepository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Component
public class UserVerificationService {

    private final UserVerificationRepository userVerificationRepository;

    @Autowired
    public UserVerificationService(UserVerificationRepository userVerificationRepository) {
        this.userVerificationRepository = userVerificationRepository;
    }

}
