package com.workruit.us.application.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.workruit.us.application.repositories.UserExpiredTokenRepository;

/**
 * Generated by Spring Data Generator on 25/11/2022
 */
@Component
public class UserExpiredTokenService {

    private final UserExpiredTokenRepository userExpiredTokenRepository;

    @Autowired
    public UserExpiredTokenService(UserExpiredTokenRepository userExpiredTokenRepository) {
        this.userExpiredTokenRepository = userExpiredTokenRepository;
    }

}
